### ISSUE TITLE
showErrorsOnlyIfInputDirty config throws an error

### ISSUE THREAD

**Issue by edernegrete** [DmitryEfimenko/ngx-messages#4]
When I write the configuration for showErrorsOnlyIfInputDirty, it throws this error:

ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'none'. Current value: 'block'.

**Comment by DmitryEfimenko** [comment]
PRs are welcome!

**Comment by DmitryEfimenko** [comment]
Closing in favor of the use of https://github.com/ngspot/ngx-errors
