### ISSUE TITLE
ERROR with AOT compiler

### ISSUE THREAD

**Issue by stocksr** [DmitryEfimenko/ngx-messages#5]
ERROR in ./node_modules/ngx-messages/index.ts
Module build failed: Error: ..\node_modules\ngx-messages\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:653:23)
    at plugin.done.then (node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./src/app/app.module.ngfactory.js 146:0-43
 @ ./src/main.ts

**Comment by stocksr** [comment]
Should have mentioned  this was introduced by the update from 

angular 5.1.1 & angular/cli 1.6.1  
to
angular 5.1.3 & angular/cli 1.6.3

**Comment by DmitryEfimenko** [comment]
PR is welcome!

**Comment by DmitryEfimenko** [comment]
this is potentially fixed in 0.3.0
